apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t4vo9w4nc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t4vo9w4nc-python 
  name: t4vo9w4nc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t4vo9w4nc-python 
